baseURL = "http://www.theswampdonkeys.com/"
languageCode = "en-us"
title = "The Swamp Donkeys"
staticDir = ["static"]
ignoreFiles = ["\\.scss$", "\\.bat$", "\\.sass$", "sass/.*"]
uglyurls = false
googleAnalytics = "UA-91862758-1"